name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - name: Clone-down
      uses: actions/checkout@v3 
    - name: my-step
      run: ci/build-app.sh
    - name: Test
      run: ci/unit-test-app.sh
    - name: Upload Repo
      uses: actions/upload-artifact@v3
      with: 
        name: code
        path: app/build/libs/app-0.1-all.jar
    - name: print workflow dump
      run: echo '${{ toJson(github) }}'
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: download artifact 
        uses: actions/download-artifact@v3
        with:
          name: code
          path: app/build/libs/app-0.1-all.jar
        env:
          docker_username: ${{ GustavFrandsen }}
          docker_password: ${{ secrets.GITHUB_TOKEN }}
